### PR TITLE
replace filter radios with icons

### LINKED ISSUE #9: Change Filter Radios to Icons
- [ ] Use the provided sprite atlas ripped from the game
- [ ] Make sure to add `alt` attributes with the name for the filter

atlas

### PR DESCRIPTION
**Pull request by devkennyy**
Screenshot
image
Before
image
After
image

All icons have alt text (Trap, Personality, etc.) and are 50x50 in size. @KarlTheCool double check size please 🙏🏻 

Fixes #9

### CODE REVIEW

**Comment by x3cca** [comment]
Thanks!!

**Review by CoolDotty — APPROVED** [review]
Yes I approve github thanks

**Comment by devkennyy** [comment]
Suggested edit:
```diff
diff --git a/.eslintrc.js b/.eslintrc.js
index 519d1ac..02fe475 100644
--- a/.eslintrc.js
+++ b/.eslintrc.js
@@ -10,7 +10,6 @@ module.exports = {
   rules: {
     'react/prop-types': 0,
     'react/jsx-props-no-spreading': 0,
-    'prefer-arrow-callback': 0,
   },
   overrides: [
     {
diff --git a/package.json b/package.json
index 0067201..e88c63b 100644
--- a/package.json
+++ b/package.json
@@ -22,7 +22,7 @@
     "web-vitals": "^2.1.4"
   },
   "scripts": {
-    "start": "export PUBLIC_URL='/'; react-scripts start",
+    "start": "cross-env PUBLIC_URL=/ react-scripts start",
     "build": "react-scripts build",
     "test": "react-scripts test",
     "predeploy": "npm run build",
@@ -49,6 +49,7 @@
     ]
   },
   "devDependencies": {
+    "cross-env": "^7.0.3",
     "eslint-plugin-react": "^7.33.2"
   }
 }
diff --git a/src/App.css b/src/App.css
index ef3a6d9..99e026d 100644
--- a/src/App.css
+++ b/src/App.css
@@ -34,6 +34,71 @@ html, body {
   max-width: 90rem;
 }
 
+.filterButton > div {
+    transition: transform 0.1s;
+    transform: scale(1.0);
+}
+
+.filterButton:hover > div,
+.filterButton:active > div,
+.filterButton.checked > div {
+    transform: scale(0.9);
+}
+
+.react-select {
+    width: 4em;
+    background-color: rgb(242, 175, 28);
+    border: solid rgb(200, 144, 21) 0;
+    border-bottom: solid rgb(200, 144, 21) 0.2em;
+    outline: solid black 0.1em;
+    border-radius: 0.5rem;
+    padding: 0 0.5rem;
+    padding-bottom: 0.5rem;
+    user-select: none;
+
+    transition: border-color 0.1s, background-color 0.1s, color 0.1s, outline 0.1s;
+}
+
+.react-select *[class$="placeholder"] {
+    transition: transform 0.1s;
+    transform: scale(1.0);
+}
+
+.react-select:hover *[class$="placeholder"] {
+    transform: scale(0.9);
+}
+
+.react-select:hover {
+    border-color: transparent;
+    outline: solid white 0.1em;
+}
+
+/* I hate css in js :cry: */
+.react-select *[class$="menu"] {
+    background-color: rgb(242, 175, 28);
+    border: solid rgb(200, 144, 21) 0;
+    border-bottom: solid rgb(200, 144, 21) 0.2em;
+    outline: solid black 0.1em;
+    border-radius: 0.5rem;
+}
+
+.react-select *[class$="option"] {
+    transition: transform 0.1s, color 0.1s;
+    transform: scale(1.0);
+    color: white;
+}
+
+.react-select *[class$="option"]:hover {
+    transform: scale(0.9);
+    color: rgb(255, 71, 178);
+}
+
+.react-select *[class$="placeholder"],
+.react-select *[class$="singleValue"],
+.react-select *[class$="option"] {
+    padding: 0 1rem;
+}
+
 .myDeck {
     position: relative;
     min-height: 30rem;
@@ -66,15 +131,10 @@ html, body {
     background-repeat: no-repeat;
 }
 
-.topMenuContainer {
+.topMenu {
     position: sticky;
     top: 1rem;
     z-index: 10;
-    margin-top: 1rem;
-    margin-bottom: 2.5rem;
-}
-
-.topMenu {
     display: flex;
     gap: 1rem;
     flex-wrap: wrap;
@@ -82,6 +142,8 @@ html, body {
     align-items: center;
 
     padding: 0.5rem 1rem ;
+    margin-top: 1rem;
+    margin-bottom: 2.5rem;
     border: solid rgb(68, 51, 154) 0;
     border-bottom: solid rgb(68, 51, 154) 0.1em;
     outline: solid black 0.1em;
@@ -89,27 +151,6 @@ html, body {
     background-color: rgb(84, 64, 187);
 }
 
-.topMenu > * {
-    flex-basis: 1px;
-    flex-grow: 1;
-    display: flex;
-    justify-content: center;
-    align-items: center;
-}
-
-.topMenu > *:first-child {
-    justify-content: start;
-}
-
-.topMenu > *:last-child {
-    justify-content: end;
-}
-
-.topMenu > .costMenu {
-    display: flex;
-    gap: 1rem;
-}
-
 .title {
     display: flex;
     align-items: center;
@@ -129,38 +170,11 @@ html, body {
         display: none;
     }
 }
+  
 
-.ShareMenu {
-    position: absolute;
-    bottom: 0;
-    right: 0.5rem; /* Same as .topMenu border radius */
-    z-index: -1;
-
+.topMenu > .costMenu {
     display: flex;
-    align-items: center;
-
-    width: calc(100% - 1rem);
-    padding: 1rem;
-
-    background-color: rgb(42, 21, 82);
-    border: solid white 0.25rem;
-    border-top: rgb(42, 21, 82);
-    outline: solid black 0.25rem;
-    border-bottom-left-radius: 1rem; 
-    border-bottom-right-radius: 1rem; 
-
-    font-size: 0.7em;
-
-    transform-origin: top;
-    transition: transform 0.1s;
-}
-
-.ShareMenu > label {
-    flex: 0 0 auto;
-}
-
-.ShareMenu > input {
-    flex: 1 1 auto;
+    gap: 1rem;
 }
 
 .filters {
@@ -186,22 +200,52 @@ html, body {
     flex-wrap: wrap;
 }
 
+.filterButton {
+    background-color: rgb(242, 175, 28);
+    border: solid rgb(200, 144, 21) 0;
+    border-bottom: solid rgb(200, 144, 21) 0.2em;
+    outline: solid black 0.1em;
+    border-radius: 0.5rem;
+    padding: 0.1rem 0.5rem;
+    padding-bottom: 0.5rem;
+    user-select: none;
+
+    transition: border-color 0.1s, background-color 0.1s, color 0.1s, outline 0.1s;
+}
+
+.filterButton:hover {
+    border-color: transparent;
+    outline: solid white 0.1em;
+}
+
+.filterButton:active {
+    border-color: transparent;
+    background-color: white;
+}
+
+.filterButton.checked {
+    border-color: transparent;
+    background-color: white;
+    color: rgb(255, 71, 178);
+}
+
+.filterButton > div {
+    transition: transform 0.1s;
+    transform: scale(1.0);
+}
+
+.filterButton:hover > div,
+.filterButton:active > div,
+.filterButton.checked > div {
+    transform: scale(0.9);
+}
+
 .content {
     display: flex;
     gap: 1rem;
     flex-wrap: wrap;
     align-items: flex-start;
     margin: 0 1rem;
-    min-height: 30rem;
-}
-
-.content > .error {
-    display: grid;
-    place-items: center;
-    width: 100%;
-    min-height: 30rem;
-    opacity: 0.5;
-    text-align: center;
 }
 
 footer {
diff --git a/src/App.jsx b/src/App.jsx
index 8b6d3a2..6736b80 100644
--- a/src/App.jsx
+++ b/src/App.jsx
@@ -1,13 +1,10 @@
 import './reset.css';
 import './App.css';
-import React, { useState, useEffect, useRef } from 'react';
+import React, { useState, useEffect } from 'react';
 import { useSearchParams } from 'react-router-dom';
 // eslint-disable-next-line import/no-extraneous-dependencies
+import Select from 'react-select';
 import Card from './Card';
-import Radio from './Radio';
-import DropDown from './DropDown';
-import Button from './Button';
-import TextInput from './TextInput';
 
 // Compressed decks strings seem to be longer than uncompressed ones
 // import { compressUrlSafe, decompressUrlSafe } from 'urlsafe-lzma';
@@ -63,30 +60,7 @@ export default function App() {
   }, [myDeck, setSearchParams]);
 
   const [cardFilter, setCardFilter] = useState('All');
-  const [cardSearch, setCardSearch] = useState('');
   const [cardSort, setCardSort] = useState('id');
-  const [shareMenuOpen, setShareMenuOpen] = useState(false);
-  const [successfulCopies, setSuccessfulCopies] = useState([]);
-
-  const copyPasteRef = useRef();
-
-  const tryToCopy = async (e) => {
-    copyPasteRef.current.focus();
-    copyPasteRef.current.setSelectionRange(0, window.location.href.length);
-    try {
-      await navigator.clipboard.writeText(window.location.href);
-      setSuccessfulCopies((copies) => {
-        const c = [...copies, {
-          id: Date.now().toString(36), // :)
-          x: e.clientX,
-          y: e.clientY,
-        }];
-        return c;
-      });
-    } catch {
-      // It's all good, we open the fallback option regardless
-    }
-  };
 
   const deckCost = myCards
     .reduce((acc, c) => acc + c.cost, 0);
@@ -95,78 +69,30 @@ export default function App() {
 
   const deckIsEmpty = myDeck.length <= 0;
 
-  const filteredAndSortedContentCard = allCards
-    .filter((c) => (
-      cardFilter !== 'All'
-        ? c.type === cardFilter
-        : c.type !== 'Personality'
-    ))
-    .filter((c) => (
-      cardSearch.length > 0
-        ? c.name.toLowerCase().includes(cardSearch.toLowerCase())
-        : true
-    ))
-    .sort(cardSorters[cardSort]);
-
   return (
     <div className="App">
-      {successfulCopies.map((s) => (
-        <CopiedPopup
-          key={s.id}
-          event={s}
-          onDone={() => {
-            setSuccessfulCopies((prevState) => prevState.filter((sc) => sc !== s));
-          }}
-        />
-      ))}
-      <div className="topMenuContainer">
-        <div className="topMenu">
-          <div className="title">
-            <img className="logo" src="./favicon.ico" alt="" />
-            <span className="text">
-              FvF Deck Builder
-            </span>
-          </div>
-          <div className="costMenu">
-            <span>
-              Cost:
-              {' '}
-              {deckCost > MAX_COST ? <b style={{ color: 'red' }}>{deckCost}</b> : deckCost}
-              /
-              {MAX_COST}
-            </span>
-            <span>
-              Count:
-              {' '}
-              {deckCount < MIN_CARDS ? <b style={{ color: 'red' }}>{deckCount}</b> : deckCount}
-              /
-              {MIN_CARDS}
-            </span>
-          </div>
-          <div>
-            <Button
-              onClick={() => setShareMenuOpen(!shareMenuOpen)}
-              label="Share"
-              forceActive={shareMenuOpen}
-            />
-          </div>
+      <div className="topMenu">
+        <div className="title">
+          <img className="logo" src="./favicon.ico" alt="" />
+          <span className="text">
+            FvF Deck Builder
+          </span>
         </div>
-        <div
-          className="ShareMenu"
-          style={{
-            transform: `translate(0%, 100%) scale(1.0, ${shareMenuOpen ? 1.0 : 0.0})`,
-          }}
-        >
-          {/* eslint-disable-next-line jsx-a11y/label-has-associated-control */}
-          <label htmlFor="ShareCopyPastInput">Link:&nbsp;</label>
-          <TextInput
-            id="ShareCopyPastInput"
-            ref={copyPasteRef}
-            type="text"
-            value={window.location.href}
-            readOnly
-            onClick={tryToCopy}
-          />
+        <div className="costMenu">
+          <span>
+            Cost:
+            {' '}
+            {deckCost > MAX_COST ? <b style={{ color: 'red' }}>{deckCost}</b> : deckCost}
+            /
+            {MAX_COST}
+          </span>
+          <span>
+            Count:
+            {' '}
+            {deckCount < MIN_CARDS ? <b style={{ color: 'red' }}>{deckCount}</b> : deckCount}
+            /
+            {MIN_CARDS}
+          </span>
         </div>
       </div>
       <div className={`myDeck ${deckIsEmpty ? 'hello' : ''}`}>
@@ -239,73 +165,94 @@ export default function App() {
         }
       </div>
       <div className="filters">
-        <div className="cardTypes">
-          <Radio
-            options={[
-              { label: 'All', value: 'All', icon: null },
-              { label: 'Personality', value: 'Personality', icon: 'personality_icon.png' },
-              { label: 'Buff', value: 'Buff', icon: 'buff_icon.png' },
-              { label: 'Debuff', value: 'Debuff', icon: 'debuff_icon.png' },
-              { label: 'Weapon', value: 'Weapon', icon: 'weapon_icon.png' },
-              { label: 'Helper', value: 'Helper', icon: 'helper_icon.png' },
-              { label: 'Wild', value: 'Wild', icon: 'wild_icon.png' },
-              { label: 'Trap', value: 'Trap', icon: 'trap_icon.png' },
-            ]}
-            value={cardFilter}
-            onChange={setCardFilter}
-          />
-        </div>
-        <div style={{ display: 'flex', alignItems: 'center' }}>
-          Search:&nbsp;
-          <TextInput
-            value={cardSearch}
-            onChange={setCardSearch}
-            style={{ width: 'calc(100% - 5em)' }}
-          />
+      <div className='cardTypes'>
+          {[
+            { type: 'All', icon: null },
+            { type: 'Personality', icon: 'personality_icon.png' },
+            { type: 'Buff', icon: 'buff_icon.png' },
+            { type: 'Debuff', icon: 'debuff_icon.png' },
+            { type: 'Weapon', icon: 'weapon_icon.png' },
+            { type: 'Helper', icon: 'helper_icon.png' },
+            { type: 'Wild', icon: 'wild_icon.png' },
+            { type: 'Trap', icon: 'trap_icon.png' },
+          ].map((filterOption) => (
+            <label
+              className={`filterButton ${
+                filterOption.type === cardFilter ? 'checked' : ''
+              }`}
+              key={`cardtype${filterOption.type}`}
+              htmlFor={filterOption.type}
+              style={{
+                display: 'flex',
+                alignItems: 'center', // Center vertically
+                justifyContent: 'center', // Center horizontally
+              }}
+            >
+              <input
+                id={filterOption.type}
+                style={{ display: 'none' }}
+                type='radio'
+                name='cardFilters'
+                value={filterOption.type}
+                checked={filterOption.type === cardFilter}
+                onChange={() => setCardFilter(filterOption.type)}
+              />
+              {filterOption.icon ? (
+                <img
+                  src={`/icons/${filterOption.icon}`}
+                  alt={filterOption.type}
+                  style={{ width: '50px', height: '50px' }}
+                />
+              ) : null}
+              {filterOption.type === 'All' ? 'All' : ''}
+            </label>
+          ))}
         </div>
         <div style={{ display: 'flex', alignItems: 'center' }}>
           Sort:&nbsp;
-          <DropDown
+          <Select
+            components={{ DropdownIndicator: () => null, IndicatorSeparator: () => null }}
+            isSearchable={false}
+            className="react-select"
+            placeholder={cardSort}
             options={[
               { value: 'id', label: 'ID' },
               { value: 'cost', label: 'Cost' },
               { value: 'type', label: 'Type' },
               // { value: 'rarity', label: 'Rarity' },
             ]}
+            unstyled
             value={cardSort}
             onChange={(option) => setCardSort(option.value)}
+            clearable={false}
           />
         </div>
       </div>
       <div className="content">
-        {filteredAndSortedContentCard.length > 0
-          ? filteredAndSortedContentCard
-            .map((c) => (
-              <Card
-                card={c}
-                equipped={myDeck.find((m) => m.id === c.id)}
-                onClick={() => {
-                  const i = myDeck.findIndex((m) => m.id === c.id);
-                  if (i >= 0) {
-                    const newDeck = [...myDeck];
-                    newDeck.splice(i, 1);
-                    setMyDeck(newDeck);
-                  } else {
-                    setMyDeck([...myDeck, c]);
-                  }
-                }}
-                key={`content${c.id}`}
-              />
-            ))
-          : (
-            <div className="error">
-              No results for &ldquo;
-              {cardSearch}
-              &rdquo;
-              <br />
-              💔
-            </div>
-          )}
+        {allCards
+          .filter((c) => (
+            cardFilter !== 'All'
+              ? c.type === cardFilter
+              : c.type !== 'Personality'
+          ))
+          .sort(cardSorters[cardSort])
+          .map((c) => (
+            <Card
+              card={c}
+              equipped={myDeck.find((m) => m.id === c.id)}
+              onClick={() => {
+                const i = myDeck.findIndex((m) => m.id === c.id);
+                if (i >= 0) {
+                  const newDeck = [...myDeck];
+                  newDeck.splice(i, 1);
+                  setMyDeck(newDeck);
+                } else {
+                  setMyDeck([...myDeck, c]);
+                }
+              }}
+              key={`content${c.id}`}
+            />
+          ))}
       </div>
       <footer>
         <div>
@@ -325,42 +272,11 @@ export default function App() {
           {' '}
           <a href="https://github.com/KarlTheCool/fvf-decks">open-source project</a>
           {' '}
-          maintained with 💔 by all its contributors
+          maintained with 💔 by
+          {' '}
+          <a href="https://ka.rlphilli.ps/">Karl Phillips</a>
         </div>
       </footer>
     </div>
   );
 }
-
-const COPIED_POPUP_TIMEOUT = 500;
-function CopiedPopup(props) {
-  const { event, onDone } = props;
-
-  const copiedRef = useRef();
-
-  useEffect(() => {
-    const me = copiedRef.current;
-    me.style.transition = `opacity ${COPIED_POPUP_TIMEOUT}ms, transform ${COPIED_POPUP_TIMEOUT}ms`;
-    me.style.opacity = 0.0;
-    me.style.transform = 'translate(-50%, -150%)';
-    setTimeout(onDone, COPIED_POPUP_TIMEOUT);
-    // eslint-disable-next-line react-hooks/exhaustive-deps
-  }, []);
-
-  return (
-    <div
-      aria-hidden
-      ref={copiedRef}
-      style={{
-        position: 'fixed',
-        top: `${event.y}px`,
-        left: `${event.x}px`,
-        zIndex: 999,
-        transform: 'translate(-50%, -50%)',
-        pointerEvents: 'none',
-      }}
-    >
-      Copied!
-    </div>
-  );
-}
diff --git a/src/Button/index.jsx b/src/Button/index.jsx
deleted file mode 100644
index 95007e3..0000000
--- a/src/Button/index.jsx
+++ /dev/null
@@ -1,18 +0,0 @@
-import React from 'react';
-
-import './styles.css';
-
-export default function Button(props) {
-  const { onClick, label, forceActive } = props;
-
-  return (
-    <button
-      type="button"
-      className={`Button ${forceActive ? 'forceActive' : ''}`}
-      onClick={onClick}
-      aria-label={label}
-    >
-      <div>{label}</div>
-    </button>
-  );
-}
diff --git a/src/Button/styles.css b/src/Button/styles.css
deleted file mode 100644
index 55be157..0000000
--- a/src/Button/styles.css
+++ /dev/null
@@ -1,68 +0,0 @@
-.Button {
-  background: none;
-  color: inherit;
-  border: none;
-
-  font-family: 'Friendly Fire';
-  text-transform: uppercase;
-  text-shadow:
-    /* Basic Outline */
-    -0.1em -0.1em 0 #000,
-     0.1em -0.1em 0 #000,
-    -0.1em  0.1em 0 #000,
-     0.1em  0.1em 0 #000,
-     0.0em -0.1em 0 #000,
-     0.1em  0.0em 0 #000,
-     0.0em  0.1em 0 #000,
-    -0.1em  0.0em 0 #000;
-  letter-spacing: 0.1em;
-
-  background-color: rgb(242, 175, 28);
-  border: solid rgb(200, 144, 21) 0;
-  border-bottom: solid rgb(200, 144, 21) 0.2em;
-  outline: solid black 0.1em;
-  border-radius: 0.5rem;
-  padding: 0.1rem 0.5rem;
-  padding-bottom: 0.5rem;
-  user-select: none;
-
-  transition: border-color 0.1s, background-color 0.1s, color 0.1s, outline 0.1s;
-}
-
-.Button:hover {
-  border-color: transparent;
-  outline: solid white 0.1em;
-}
-
-.Button:active {
-  border-color: transparent;
-  background-color: white;
-}
-
-.Button.forceActive  {
-  border-color: transparent;
-  background-color: white;
-  color: rgb(255, 71, 178);
-}
-
-.Button > div {
-  transition: transform 0.1s;
-  transform: scale(1.0);
-}
-
-.Button:hover > div,
-.Button:active > div,
-.Button.forceActive > div {
-  transform: scale(0.9);
-}
-
-.Button > * {
-  transition: transform 0.1s;
-  transform: scale(1.0);
-}
-
-.Button:hover > *,
-.Button:active > *,
-.Button.forceActive > * {
-  transform: scale(0.9);
-}
diff --git a/src/DropDown/index.jsx b/src/DropDown/index.jsx
deleted file mode 100644
index 15bde95..0000000
--- a/src/DropDown/index.jsx
+++ /dev/null
@@ -1,25 +0,0 @@
-import React from 'react';
-import Select from 'react-select';
-
-import './styles.css';
-
-export default function DropDown(props) {
-  const {
-    options,
-    value,
-    onChange,
-  } = props;
-  return (
-    <Select
-      components={{ DropdownIndicator: () => null, IndicatorSeparator: () => null }}
-      isSearchable={false}
-      className="react-select"
-      placeholder={value}
-      options={options}
-      unstyled
-      value={value}
-      onChange={(option) => onChange(option)}
-      clearable={false}
-    />
-  );
-}
diff --git a/src/DropDown/styles.css b/src/DropDown/styles.css
deleted file mode 100644
index 178b6f6..0000000
--- a/src/DropDown/styles.css
+++ /dev/null
@@ -1,53 +0,0 @@
-.react-select {
-  width: 4em;
-  background-color: rgb(242, 175, 28);
-  border: solid rgb(200, 144, 21) 0;
-  border-bottom: solid rgb(200, 144, 21) 0.2em;
-  outline: solid black 0.1em;
-  border-radius: 0.5rem;
-  padding: 0 0.5rem;
-  padding-bottom: 0.5rem;
-  user-select: none;
-
-  transition: border-color 0.1s, background-color 0.1s, color 0.1s, outline 0.1s;
-}
-
-.react-select *[class$="placeholder"] {
-  transition: transform 0.1s;
-  transform: scale(1.0);
-}
-
-.react-select:hover *[class$="placeholder"] {
-  transform: scale(0.9);
-}
-
-.react-select:hover {
-  border-color: transparent;
-  outline: solid white 0.1em;
-}
-
-/* I hate css in js :cry: */
-.react-select *[class$="menu"] {
-  background-color: rgb(242, 175, 28);
-  border: solid rgb(200, 144, 21) 0;
-  border-bottom: solid rgb(200, 144, 21) 0.2em;
-  outline: solid black 0.1em;
-  border-radius: 0.5rem;
-}
-
-.react-select *[class$="option"] {
-  transition: transform 0.1s, color 0.1s;
-  transform: scale(1.0);
-  color: white;
-}
-
-.react-select *[class$="option"]:hover {
-  transform: scale(0.9);
-  color: rgb(255, 71, 178);
-}
-
-.react-select *[class$="placeholder"],
-.react-select *[class$="singleValue"],
-.react-select *[class$="option"] {
-  padding: 0 1rem;
-}
diff --git a/src/Radio/index.jsx b/src/Radio/index.jsx
deleted file mode 100644
index 7f831e2..0000000
--- a/src/Radio/index.jsx
+++ /dev/null
@@ -1,43 +0,0 @@
-import React, { } from 'react';
-
-import './styles.css';
-
-export default function Radio(props) {
-  const {
-    options,
-    onChange,
-    value,
-  } = props;
-
-  return (
-    <>
-      {options.map((o) => (
-        <label
-          className={`radio ${o.value === value ? 'checked' : ''}`}
-          key={`cardtype${o.value}`}
-          htmlFor={o.value}
-          style={{
-            display: 'grid',
-            placeItems: 'center',
-          }}
-        >
-          <input
-            id={o.value}
-            style={{ display: 'none' }}
-            type="radio"
-            value={o.value}
-            checked={o.value === value}
-            onChange={() => onChange(o.value)}
-          />
-          {o.icon ? (
-            <img
-              src={`/icons/${o.icon}`}
-              alt={o.label}
-              style={{ width: '1em', height: '1em' }}
-            />
-          ) : <div>{o.label}</div>}
-        </label>
-      ))}
-    </>
-  );
-}
diff --git a/src/Radio/styles.css b/src/Radio/styles.css
deleted file mode 100644
index 7c1bff7..0000000
--- a/src/Radio/styles.css
+++ /dev/null
@@ -1,65 +0,0 @@
-
-.radio {
-  background-color: rgb(242, 175, 28);
-  border: solid rgb(200, 144, 21) 0;
-  border-bottom: solid rgb(200, 144, 21) 0.2em;
-  outline: solid black 0.1em;
-  border-radius: 0.5rem;
-  padding: 0.1rem 0.5rem;
-  padding-bottom: 0.5rem;
-  user-select: none;
-
-  font-family: 'Friendly Fire';
-  text-transform: uppercase;
-  text-shadow:
-    /* Basic Outline */
-    -0.1em -0.1em 0 #000,
-     0.1em -0.1em 0 #000,
-    -0.1em  0.1em 0 #000,
-     0.1em  0.1em 0 #000,
-     0.0em -0.1em 0 #000,
-     0.1em  0.0em 0 #000,
-     0.0em  0.1em 0 #000,
-    -0.1em  0.0em 0 #000;
-  letter-spacing: 0.1em;
-
-  transition: border-color 0.1s, background-color 0.1s, color 0.1s, outline 0.1s;
-}
-
-.radio:hover {
-  border-color: transparent;
-  outline: solid white 0.1em;
-}
-
-.radio:active {
-  border-color: transparent;
-  background-color: white;
-}
-
-.radio.checked {
-  border-color: transparent;
-  background-color: white;
-  color: rgb(255, 71, 178);
-}
-
-.radio > div {
-  transition: transform 0.1s;
-  transform: scale(1.0);
-}
-
-.radio:hover > div,
-.radio:active > div,
-.radio.checked > div {
-  transform: scale(0.9);
-}
-
-.radio > * {
-  transition: transform 0.1s;
-  transform: scale(1.0);
-}
-
-.radio:hover > *,
-.radio:active > *,
-.radio.checked > * {
-  transform: scale(0.9);
-}
diff --git a/src/TextInput/index.jsx b/src/TextInput/index.jsx
deleted file mode 100644
index 7394ca0..0000000
--- a/src/TextInput/index.jsx
+++ /dev/null
@@ -1,18 +0,0 @@
-import React, { forwardRef } from 'react';
-
-import './styles.css';
-
-export default forwardRef(function TextInput(props, ref) {
-  const { value, onChange, ...rest } = props;
-
-  return (
-    <input
-      type="text"
-      className="TextInput"
-      value={value}
-      onChange={(e) => onChange(e.target.value)}
-      ref={ref}
-      {...rest}
-    />
-  );
-});
diff --git a/src/TextInput/styles.css b/src/TextInput/styles.css
deleted file mode 100644
index 6efac25..0000000
--- a/src/TextInput/styles.css
+++ /dev/null
@@ -1,18 +0,0 @@
-.TextInput {
-  background: none;
-  color: inherit;
-  border: none;
-
-  font-family: 'Friendly Fire';
-  font-size: 1.25rem;
-  letter-spacing: 0.1em;
-
-  background-color: rgb(22, 13, 46);
-  border: solid rgb(240 238 218) 0.25rem;
-  border-radius: 0.75rem;
-  padding: 0.5rem;
-}
-
-.TextInput:focus {
-  outline: none;
-}
diff --git a/yarn.lock b/yarn.lock
index 7ad4cf8..b7b4d03 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -3561,7 +3561,14 @@ cosmiconfig@^7.0.0:
     path-type "^4.0.0"
     yaml "^1.10.0"
 
-cross-spawn@^7.0.2, cross-spawn@^7.0.3:
+cross-env@^7.0.3:
+  version "7.0.3"
+  resolved "https://registry.yarnpkg.com/cross-env/-/cross-env-7.0.3.tgz#865264b29677dc015ba8418918965dd232fc54cf"
+  integrity sha512-+/HKd6EgcQCJGh2PSjZuUitQBQynKor4wrFbRg4DtAgS1aWO+gU52xpH7M9ScGgXSYmAVS9bIJ8EzuaGw0oNAw==
+  dependencies:
+    cross-spawn "^7.0.1"
+
+cross-spawn@^7.0.1, cross-spawn@^7.0.2, cross-spawn@^7.0.3:
   version "7.0.3"
   resolved "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.3.tgz"
   integrity sha512-iRDPJKUPVEND7dHPO8rkbOnPpyDygcDFtWjpeWNCgy8WP2rXcxXL8TskReQl6OrB2G7+UJrags1q15Fudc7G6w==

```

**Comment by x3cca** [comment]
What does this do?

**Pull request merged**
